<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Slim 3</title>
    <link rel="stylesheet" href="js/libs/bootstrap/dist/css/bootstrap.min.css"/>
</head>
<body>
<div class="container">
    <div class="row">
        <?php if ($employee): ?>
            <div class="col-sm-12">
                <h4>Employee details</h4>
            </div>
            <div class="col-sm-12">
                <div class="col-sm-2 text-right">Name:</div>
                <div class="col-sm-10 text-left"><?php echo $employee->name ?></div>
            </div>
            <div class="col-sm-12">
                <div class="col-sm-2 text-right">Email:</div>
                <div class="col-sm-10 text-left"><?php echo $employee->email ?></div>
            </div>
            <div class="col-sm-12">
                <div class="col-sm-2 text-right">Phone:</div>
                <div class="col-sm-10 text-left"><?php echo $employee->phone ?></div>
            </div>
            <div class="col-sm-12">
                <div class="col-sm-2 text-right">Address:</div>
                <div class="col-sm-10 text-left"><?php echo $employee->address ?></div>
            </div>
            <div class="col-sm-12">
                <div class="col-sm-2 text-right">Position:</div>
                <div class="col-sm-10 text-left"><?php echo $employee->position ?></div>
            </div>
            <div class="col-sm-12">
                <div class="col-sm-2 text-right">Salary:</div>
                <div class="col-sm-10 text-left"><?php echo $employee->salary ?></div>
            </div>
            <div class="col-sm-12">
                <div class="col-sm-2 text-right">Skills:</div>
                <div class="col-sm-10 text-left"><?php echo $skills ?></div>
            </div>
        <?php else: ?>
            <div class="col-sm-12">
                <h4>Employee doesn't exist</h4>
            </div>
        <?php endif; ?>
    </div>
</div>
</body>
</html>
