<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Slim 3</title>
    <link rel="stylesheet" href="js/libs/bootstrap/dist/css/bootstrap.min.css"/>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h2>Employees</h2>
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Position</th>
                    <th>Salary</th>
                    <th>Options</th>
                </tr>
                </thead>
                <tbody>
                <?php $count = 1; ?>
                <?php foreach ($lstEmployees as $key => $employee): ?>
                    <tr>
                        <th scope="row"><?php echo $count ?></th>
                        <td><?php echo $employee->name ?></td>
                        <td><?php echo $employee->email ?></td>
                        <td><?php echo $employee->position ?></td>
                        <td><?php echo $employee->salary ?></td>
                        <td>
                            <a href="" class="btn btn-primary">
                                <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                            </a>
                        </td>
                    </tr>
                    <?php $count++; ?>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
</body>
</html>
