<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Slim 3</title>
    <link rel="stylesheet" href="js/libs/bootstrap/dist/css/bootstrap.min.css"/>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h2>Employees</h2>

            <div class="col-sm-12" style="margin: 20px 0">
                <form action="" method="GET">
                    <div class="col-sm-1 text-right" style="margin-top: 5px">Email:</div>
                    <div class="col-sm-4">
                        <input class="form-control" type="text" id="email" name="email" value="<?php echo $email ?>"/>
                    </div>
                    <div class="col-sm-6">
                        <button id="btn_search" class="btn btn-primary" type="submit">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        </button>
                    </div>
                </form>
            </div>

            <table class="table table-striped">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Position</th>
                    <th>Salary</th>
                    <th>Options</th>
                </tr>
                </thead>
                <tbody id="container-employees">
                <?php $count = 1; ?>
                <?php foreach ($lstEmployees as $key => $employee): ?>
                    <tr>
                        <th scope="row"><?php echo $count ?></th>
                        <td><?php echo $employee->name ?></td>
                        <td><?php echo $employee->email ?></td>
                        <td><?php echo $employee->position ?></td>
                        <td><?php echo $employee->salary ?></td>
                        <td>
                            <a href="<?php echo $employee->id ?>" class="btn btn-primary">
                                <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                            </a>
                        </td>
                    </tr>
                    <?php $count++; ?>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<script src="js/libs/jquery/dist/jquery.min.js"></script>
<script src="js/app.js"></script>
</body>
</html>
